# 베이스 이미지 (Node.js)
FROM node:14

# 작업 디렉토리
WORKDIR /app

# 패키지 파일 복사 및 의존성
COPY package*.json ./
RUN npm install

# 애플리케이션 코드 복사
COPY . .

# 애플리케이션 빌드
RUN npm run build

# 애플리케이션 실행
CMD ["npm", "start"]

