#빌드
FROM node:18 AS builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

#실행
FROM node:18-alpine

WORKDIR /app
COPY --from=builder /app ./
RUN npm install --production

EXPOSE 3000

CMD ["npm", "start"]

