name: myProject 
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:dayfull@postgresql:5432/dayfullpg
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./backend/.env         # ✅ 이 줄 추가!  
    depends_on:
      - postgresql
      - redis
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads 
      - ./backend/keys:/app/keys
      - /app/node_modules
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
        - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    environment:
      - DOCKER=true
      - VITE_PORT=5173
    env_file:
      - ./frontend/.env.docker   # 도커에선 이 파일을 사용  
    networks:
      - app-network

  postgresql:
    image: postgres
    restart: always
    container_name: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dayfull
      POSTGRES_DB: dayfullpg
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  db-data:
  
networks:
  app-network:
    driver: bridge
