version: '3.8'
services:
  nestjs-api:
    build:
      context: ./backend/nestjs-api
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  spring-api:
    build:
      context: ./backend/spring-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres-data:
