name: myProject 
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:dayfull@db:5432/postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - app-network
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  postgresql:
    image: postgres
    restart: always
    container_name: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dayfull
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
